// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />
namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
    using Eco.Gameplay.Components.Storage;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;
    using Eco.Gameplay.Items.Recipes;
    
    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(OccupancyRequirementComponent))]
    [RequireComponent(typeof(MountComponent))]
    [Tag("Usable")]
    [Ecopedia("Housing Objects", "Indoor", subPageName: "VineMid Plant Item")]
    public partial class VineMidPlantObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(VineMidPlantItem);
        public override LocString DisplayName => Localizer.DoStr("VineMid Plant");
        public override TableTextureMode TableTexture => TableTextureMode.Metal;

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<HousingComponent>().HomeValue = VineMidPlantItem.homeValue;
            this.GetComponent<MountComponent>().Initialize(1);
            this.ModsPostInitialize();
        }

        protected override void OnCreatePostInitialize()
        {
            base.OnCreatePostInitialize();
            this.GetComponent<PropertyAuthComponent>().SetPublic();
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [RequiresSkill(typeof(FarmingSkill), 5)]  // Requires Farming skill level 5
    [Ecopedia("Items", "Decorations", subPageName: "VineMid Plant Item")]
    public partial class VineMidPlantRecipe : RecipeFamily
    {
        public VineMidPlantRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "VineMidPlant",  //noloc
                displayName: Localizer.DoStr("VineMid Plant"),
                
                // Ingredients needed for the recipe
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(PlantFibersItem), 10, typeof(FarmingSkill), typeof(FarmingLavishResourcesTalent)),
                },
                
                // Recipe output
                items: new List<CraftingElement>
                {
                    new CraftingElement<VineMidPlantItem>()
                });
                
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 8; // Experience gained when crafted
            
            // Labor required and associated skill
            this.LaborInCalories = CreateLaborInCaloriesValue(800, typeof(FarmingSkill));
            
            // Crafting time
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(VineMidPlantRecipe), start: 4, skillType: typeof(FarmingSkill), typeof(FarmingFocusedSpeedTalent), typeof(FarmingParallelSpeedTalent));
            
            // Pre/Post initialization
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("VineMid Plant"), recipeType: typeof(VineMidPlantRecipe));
            this.ModsPostInitialize();
            
            // Register the recipe with the crafting table
            CraftingComponent.AddRecipe(tableType: typeof(FarmersTableObject), recipeFamily: this);
        }
        
        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
	[LocDisplayName("VineMid Plant")]
	[LocDescription("An elegant indoor VineMid with graceful arching fronds that create a tropical ambiance. This compact VineMid thrives in bright indirect light and brings a touch of the exotic to any room.")]
    [Ecopedia("Housing Objects", "Indoor", createAsSubPage: true)]
    [Weight(500)]
    [Tag("Housing")]
	[MaxStackSize(30)]
	[Tag(nameof(SurfaceTags.CanBeOnSurface))]
    public partial class VineMidPlantItem : WorldObjectItem<VineMidPlantObject>
    {
        [Serialized, SyncToView, NewTooltipChildren(CacheAs.Instance, flags: TTFlags.AllowNonControllerTypeForChildren)] 
        public object PersistentData { get; set; }

        public override bool ShowLocationsInWorld => false;
		protected override OccupancyContext GetOccupancyContext => new SideAttachedContext(DirectionAxisFlags.All, WorldObject.GetOccupancyInfo(this.WorldObjectType));
        public override HomeFurnishingValue HomeValue => homeValue;
        
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName = typeof(VineMidPlantObject).UILink(),
            Category = HousingConfig.GetRoomCategory("Decoration"),
            BaseValue = 2,  // Increased the housing bonus value a bit
            TypeForRoomLimit = Localizer.DoStr("Plants"),  // Creates a category for room limit purposes
            DiminishingReturnMultiplier = 0.2f  // Adjust this to control how multiple plants affect housing
        };
    }

}